sudo: required

language: generic

services:
  - docker

before_install:
  - ./update_docker.sh
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin

install:
  - make push
  - make clean
