PROJECT_NAME = forest-fire
IMAGE_NAME = paulrb/${PROJECT_NAME}
BUILDKITE_BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD)
BUILDKITE_BUILD_NUMBER ?= 0

.PHONY: all clean push tag build

build: ## Create the docker image.
	@echo "--- :wind_chime: Building :wind_chime:"
	-docker image pull ${IMAGE_NAME}:master
	docker image build --pull \
		--cache-from ${IMAGE_NAME}:master \
		--tag ${IMAGE_NAME}:latest .

tag: build ## Tag the docker images with the build information.
	@echo "--- :label: Tagging image :label:"
	docker image tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${BUILDKITE_BRANCH}
	docker image tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${BUILDKITE_BUILD_NUMBER}

push: tag ## Push the docker image to the registry.
	@echo "--- :satellite: Pushing to docker registry :satellite:"
	docker image push ${IMAGE_NAME}:${BUILDKITE_BUILD_NUMBER}
	docker image push ${IMAGE_NAME}:${BUILDKITE_BRANCH}
	docker image push ${IMAGE_NAME}:latest

clean: ## Cleanup artifacts generated by build.
	@echo "--- :shower: Cleaning up :shower:"
	-docker container prune -f &> /dev/null
	-docker image rm ${IMAGE_NAME}:latest &> /dev/null
	-docker image rm ${IMAGE_NAME}:${BUILDKITE_BRANCH} &> /dev/null
	-docker image rm ${IMAGE_NAME}:${BUILDKITE_BUILD_NUMBER} &> /dev/null
	-docker system prune -f &> /dev/null

all: build tag push
